"""Regenerate the linear-demand Price Gain and Profit Gain panels using the
LONG-TERM collusive benchmark (p^LC = 1/2, Pi^LC = 1/4) and the static Nash
benchmark, matching the paper text (eq. linear_benchmarks and the surrounding
discussion) rather than the short-term collusive price 1/(2+gamma) that the
simulation's cycle_statistics.csv normalized against.

Gain is affine in the observed price/profit and the benchmarks are deterministic
functions of gamma, so the corrected gains are recomputed EXACTLY from the stored
mean/std of price and profit -- no re-simulation:

    Price Gain  = (p    - p^N(g)) / (p^LC   - p^N(g)),   p^LC   = 1/2
    Profit Gain = (pi   - Pi^N(g))/ (Pi^LC  - Pi^N(g)),  Pi^LC  = 1/4
    p^N(g)  = 1/(3+2g)              (n=2, c=0)
    Pi^N(g) = 2(1+g)/(3+2g)^2
    std_gain = std_{price|profit} / (benchmark span)   (affine scaling)

Only the two gain PNGs are overwritten; the price and profit panels are left as
generated by recolor_linear_td3_purple.py (purple, band = 0.8*std).

Run:  /Users/neda/llm_venv/bin/python recompute_linear_gains_longterm.py
"""
import os
import glob
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = "/Users/neda/Desktop/UBC/PHD/research_term_4"
RES = os.path.join(ROOT, "Results", "experiments")
IMG = os.path.join(ROOT, "Algorithmic-Collusion-Replication",
                   "Final_Paper__Reference_Dependence__Copy2_", "Images")

# (source experiment dir, output image dir): main Q-ref linear AND the
# appendix exponential-smoothing linear sibling -- both must use the same
# long-term benchmark so the "similar pattern" cross-reference holds.
BLOCKS = [
    (os.path.join(RES, "linear_benchmark", "gamma_only_linear_qref_beta4e-6"),
     os.path.join(IMG, "4_seperate_figures_beta4e6", "linear")),
    (os.path.join(RES, "linear_benchmark", "gamma_only_linear_beta4e-6"),
     os.path.join(IMG, "4_seperate_figures_beta4e6", "linear_es")),
]

# match recolor_linear_td3_purple.py exactly
RC = {"font.size": 18, "axes.labelsize": 18, "xtick.labelsize": 16,
      "ytick.labelsize": 16, "legend.fontsize": 14}
COLOR, LW, BAND_MULT, BAND_ALPHA = "tab:purple", 2.0, 0.8, 0.15

# long-term collusive benchmark (internalizes the reference: r = p)
P_LC, PI_LC = 0.5, 0.25


def p_nash(g):
    return 1.0 / (3.0 + 2.0 * g)          # n=2, c=0


def pi_nash(g):
    return 2.0 * (1.0 + g) / (3.0 + 2.0 * g) ** 2


def load_longterm_gain(exp_dir, which):
    """which in {'price','profit'}; returns gamma, mean_gain, std_gain arrays."""
    rows = []
    for d in sorted(glob.glob(os.path.join(exp_dir, "gamma_*"))):
        f = os.path.join(d, "cycle_statistics.csv")
        if not os.path.exists(f):
            continue
        r = pd.read_csv(f).iloc[0]
        g = float(os.path.basename(d).split("gamma_")[1])
        mu = np.mean([float(r[f"mean_{which}_p1"]), float(r[f"mean_{which}_p2"])])
        sd = np.mean([float(r[f"std_{which}_p1"]), float(r[f"std_{which}_p2"])])
        if which == "price":
            lo, hi = p_nash(g), P_LC
        else:
            lo, hi = pi_nash(g), PI_LC
        span = hi - lo
        rows.append((g, (mu - lo) / span, sd / span))
    rows.sort()
    a = np.array(rows)
    return a[:, 0], a[:, 1], a[:, 2]


if __name__ == "__main__":
    panels = [("price", "Price Gain", "figure1_gamma_only_q_price_gain.png"),
              ("profit", "Profit Gain", "figure1_gamma_only_q_profit_gain.png")]

    with plt.rc_context(RC):
        for exp_dir, out_dir in BLOCKS:
            if not os.path.isdir(exp_dir):
                print(f"!! missing source: {exp_dir}")
                continue
            os.makedirs(out_dir, exist_ok=True)
            n_g = len(glob.glob(os.path.join(exp_dir, "gamma_*")))
            print(f"linear long-term gains: {n_g} gammas  <-  {exp_dir}")
            for which, ylabel, fname in panels:
                g, mu, sd = load_longterm_gain(exp_dir, which)
                fig, ax = plt.subplots(figsize=(6, 4))
                ax.plot(g, mu, color=COLOR, lw=LW)
                ax.fill_between(g, mu - BAND_MULT * sd, mu + BAND_MULT * sd,
                                color=COLOR, alpha=BAND_ALPHA, lw=0)
                ax.set_xlabel(r"$\gamma$")
                ax.set_ylabel(ylabel)
                ax.grid(True, ls="--", alpha=0.4)
                out = os.path.join(out_dir, fname)
                fig.savefig(out, dpi=300, bbox_inches="tight")
                plt.close(fig)
                print(f"    wrote {out}  (range {mu.min():.3f}..{mu.max():.3f})")
    print("done.")
